libnixd_include = include_directories('../include')

libnixd_deps = [ nixd_lsp_server, nixf, llvm, nixt ]

libnixd_lib = library(
    'nixd',
    'CommandLine/Configuration.cpp',
    'CommandLine/Options.cpp',
    'Controller/AST.cpp',
    'Controller/CodeAction.cpp',
    'Controller/CodeActions/AddToFormals.cpp',
    'Controller/CodeActions/AttrName.cpp',
    'Controller/CodeActions/ConvertToInherit.cpp',
    'Controller/CodeActions/ExtractToFile.cpp',
    'Controller/CodeActions/FlattenAttrs.cpp',
    'Controller/CodeActions/InheritToBinding.cpp',
    'Controller/CodeActions/JsonToNix.cpp',
    'Controller/CodeActions/NoogleDoc.cpp',
    'Controller/CodeActions/PackAttrs.cpp',
    'Controller/CodeActions/RewriteString.cpp',
    'Controller/CodeActions/Utils.cpp',
    'Controller/CodeActions/WithToLet.cpp',
    'Controller/Completion.cpp',
    'Controller/Completion/AttrPath.cpp',
    'Controller/Completion/Context.cpp',
    'Controller/Completion/Literals.cpp',
    'Controller/Completion/Names.cpp',
    'Controller/Completion/Nixpkgs.cpp',
    'Controller/Completion/Packages.cpp',
    'Controller/Completion/Paths.cpp',
    'Controller/Completion/Select.cpp',
    'Controller/Completion/Snippets.cpp',
    'Controller/Completion/Value.cpp',
    'Controller/Completion/Variables.cpp',
    'Controller/Configuration.cpp',
    'Controller/Convert.cpp',
    'Controller/Definition.cpp',
    'Controller/Diagnostics.cpp',
    'Controller/DocumentHighlight.cpp',
    'Controller/DocumentLink.cpp',
    'Controller/DocumentSymbol.cpp',
    'Controller/FlakeInputInspect.cpp',
    'Controller/FoldingRange.cpp',
    'Controller/FindReferences.cpp',
    'Controller/Format.cpp',
    'Controller/Hover.cpp',
    'Controller/InlayHints.cpp',
    'Controller/LifeTime.cpp',
    'Controller/ModuleInputInspect.cpp',
    'Controller/NixTU.cpp',
    'Controller/Option/Diagnostics.cpp',
    'Controller/Option/DiagnosticsSchedule.cpp',
    'Controller/Option/DiagnosticsSupport.cpp',
    'Controller/Option/FlakeSchema.cpp',
    'Controller/Option/Integer.cpp',
    'Controller/Option/Navigation.cpp',
    'Controller/Option/Providers.cpp',
    'Controller/Option/Type.cpp',
    'Controller/Option/Validation.cpp',
    'Controller/Option/Validation/Packages.cpp',
    'Controller/Option/Validation/Paths.cpp',
    'Controller/Option/Validation/Scalars.cpp',
    'Controller/Rename.cpp',
    'Controller/SemanticTokens.cpp',
    'Controller/Support.cpp',
    'Controller/TextDocumentSync.cpp',
    'Eval/AttrSetClient.cpp',
    'Eval/AttrSetValue.cpp',
    'Eval/AttrSetProvider.cpp',
    'Eval/OptionDescription.cpp',
    'Eval/Launch.cpp',
    'Protocol/AttrSet.cpp',
    'Protocol/Protocol.cpp',
    'Support/AutoCloseFD.cpp',
    'Support/AutoRemoveShm.cpp',
    'Support/ForkPiped.cpp',
    'Support/JSON.cpp',
    'Support/PipedProc.cpp',
    'Support/StreamProc.cpp',
    dependencies: libnixd_deps,
    include_directories: libnixd_include,
    install: true
)

libnixd = declare_dependency(
    include_directories: libnixd_include,
    link_with: libnixd_lib,
    dependencies: libnixd_deps
)
